#!/usr/bin/env Rscript
# ==============================================================================
# SCRIPT:   00_generate_primers.R
# PIPELINE: SeCAT v4.1 (Sequence Consensus Amplicon Trimming)
# STAGE:    Stage 0 — Primer Database Generation (Primer Mode Only)
# PURPOSE:  Extract primer-specific subsequences from the SILVA reference to
#           build per-primer reference databases for coordinate mapping.
#
# OVERVIEW:
#   In primer-mode analysis, SeCAT needs a separate reference FASTA for each
#   primer pair, containing only the amplicon region each primer targets. This
#   script takes a single task ID (one primer pair) and extracts the
#   corresponding subsequences from the full SILVA reference alignment using
#   memory-efficient chunked streaming (~2 GB RAM vs 20+ GB for whole-file
#   loading). Each chunk of SILVA sequences is read, trimmed to the primer
#   coordinates, and appended to the output FASTA.
#
# INPUTS:
#   - Command-line argument: task ID (integer, 1-indexed, one per primer pair)
#   - output/intermediate/primer_coords_phase1_output.csv — primer coordinates
#     from 01_primer_mapping.R (columns: primer_name, primer_start, primer_end)
#   - REFERENCE_DB_PATH — full SILVA aligned FASTA (from secat_config.R)
#
# OUTPUTS:
#   - output/primer_databases/db_<primer_name>.fasta — trimmed reference
#     containing only the amplicon region for this primer pair
#
# DEPENDENCIES:
#   - Biostrings (Bioconductor): FASTA I/O and subsequence extraction
#   - R/secat_config.R: provides REFERENCE_DB_PATH
#
# CALLED BY:
#   - modules/local/primer_mapping.nf (GENERATE_PRIMER_DBS process)
#   - Only used when analysis_mode = "primer"
# ==============================================================================

# --- Force garbage collection to start with minimal memory footprint ---
# Essential on HPC nodes where multiple array jobs share memory.
gc(reset = TRUE, full = TRUE)

# --- Load Libraries & Config ---
# Biostrings: FASTA reading/writing and subsequence extraction
# dplyr/tidyr/readr: manifest and coordinate table handling
suppressPackageStartupMessages({
  library(Biostrings)
  suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(stringr))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(tibble))
})

# Load SeCAT configuration (provides REFERENCE_DB_PATH and output paths).
# Uses SECAT_PROJECTDIR env var set by Nextflow, with cwd fallback.
if (file.exists(file.path(Sys.getenv("SECAT_PROJECTDIR", getwd()), "R/secat_config.R"))) {
  source(file.path(Sys.getenv("SECAT_PROJECTDIR", getwd()), "R/secat_config.R"))
} else {
  source(file.path(Sys.getenv("SECAT_PROJECTDIR", getwd()), "R/secat_config.R"))  # Fallback
}

# Release memory allocated during config loading before heavy I/O begins.
gc(full = TRUE)

# --- Parse Task ID from Command Line ---
# In array job mode, each worker receives a unique integer identifying which
# primer pair to process. This maps to a row in primer_coords_phase1_output.csv.
args <- commandArgs(trailingOnly = TRUE)
if (length(args) == 0) stop("FATAL: SGE_TASK_ID not provided.")
task_id <- as.integer(args[1])
message(paste("Starting worker for Task ID:", task_id))

# --- Define Input/Output Paths ---
# Primer coordinates CSV was generated by 01_primer_mapping.R.
# Output directory holds one FASTA per primer pair.
PRIMER_COORDS_CSV <- "output/intermediate/primer_coords_phase1_output.csv"
OUTPUT_DIR <- "output/primer_databases"

# --- Read Primer Info for This Task ---
# Load the primer coordinates table and select the row matching this task ID.
# Each row defines a primer pair's start/end positions in SILVA alignment space.
if (!file.exists(PRIMER_COORDS_CSV)) {
  stop("FATAL: Primer coordinates file not found: ", PRIMER_COORDS_CSV)
}

primer_sets <- read_csv(PRIMER_COORDS_CSV, show_col_types = FALSE)
if (task_id > nrow(primer_sets)) {
  stop(paste("FATAL: Task ID", task_id, "is out of bounds."))
}

primer_info <- primer_sets[task_id, ]

primer_name <- primer_info$primer_name
start_pos <- primer_info$primer_start
end_pos <- primer_info$primer_end

output_fasta <- file.path(OUTPUT_DIR, paste0("db_", primer_name, ".fasta"))
message(paste("  -> Target Primer:", primer_name, "| Coords:", start_pos, "-", end_pos))

# Release primer table from memory — only the single-row info is needed.
rm(primer_sets, primer_info)
gc(full = TRUE)

# --- Validate Reference Database ---
# The full SILVA alignment must be accessible; abort early if missing.
if (!file.exists(REFERENCE_DB_PATH)) {
  stop("FATAL: Reference database not found at: ", REFERENCE_DB_PATH)
}

# ==============================================================================
# CHUNKED STREAMING EXTRACTION
# The full SILVA alignment (~600k sequences, ~50 GB uncompressed) cannot be
# loaded into memory on most HPC nodes. Instead, sequences are processed in
# chunks of 50,000 (~500 MB RAM per chunk). For each chunk:
#   1. Read sequences as BStringSet (handles alignment gap characters)
#   2. Filter to sequences long enough to span the primer region
#   3. Extract the subsequence between primer_start and primer_end
#   4. Append to the output FASTA
# This reduces peak memory from ~20 GB to ~2 GB.
# ==============================================================================
message("Using memory-efficient chunked processing...")

# Build FASTA index (fast, ~1 second, minimal memory).
# The index maps byte offsets so chunks can be read without scanning from the start.
message("  -> Building FASTA index...")
fai <- Biostrings::fasta.index(REFERENCE_DB_PATH)
n_seqs <- nrow(fai)
message(paste("     Found", n_seqs, "sequences in reference database"))

# Validate that the reference alignment is long enough to span the primer region.
message("  -> Checking sequence format...")
first_seq <- readBStringSet(REFERENCE_DB_PATH, nrec = 1)
full_len <- width(first_seq)[1]
message(paste("     Reference alignment length:", full_len, "bp"))

if (full_len < end_pos) {
  stop(paste("FATAL: Sequences (", full_len, "bp) are shorter than primer end position (", end_pos, ")!"))
}

rm(first_seq)
gc()

# Chunk size tuned for ~500 MB RAM per chunk on typical HPC nodes.
chunk_size <- 50000
n_chunks <- ceiling(n_seqs / chunk_size)

# Ensure output directory exists and clear any previous output for this primer.
if (!dir.exists(OUTPUT_DIR)) dir.create(OUTPUT_DIR, recursive = TRUE)

# Remove any existing output to avoid appending to stale data.
if (file.exists(output_fasta)) {
  message("  -> Removing existing output file...")
  file.remove(output_fasta)
}

message(paste("Processing", n_seqs, "sequences in", n_chunks, "chunks of", chunk_size, "..."))

# --- Streaming Processing Loop ---
# Iterate through SILVA in chunks, extract the primer amplicon region from
# each valid sequence, and append to the output FASTA.
total_extracted <- 0
start_time <- Sys.time()

for (chunk_id in 1:n_chunks) {
  # Calculate sequence range for this chunk
  start_idx <- (chunk_id - 1) * chunk_size + 1
  end_idx <- min(chunk_id * chunk_size, n_seqs)
  chunk_length <- end_idx - start_idx + 1
  
  # Read chunk using BStringSet (handles gaps/alignment characters)
  chunk_seqs <- tryCatch({
    readBStringSet(REFERENCE_DB_PATH, nrec = chunk_length, skip = start_idx - 1)
  }, error = function(e) {
    message(paste("WARNING: Error reading chunk", chunk_id, ":", conditionMessage(e)))
    return(NULL)
  })
  
  if (is.null(chunk_seqs) || length(chunk_seqs) == 0) {
    message(paste("  Skipping empty chunk", chunk_id))
    next
  }
  
  # Filter: Keep only sequences long enough
  all_widths <- width(chunk_seqs)
  valid_indices <- which(all_widths >= end_pos)
  
  if (length(valid_indices) > 0) {
    valid_seqs <- chunk_seqs[valid_indices]
    
    # Extract amplicon region (primer coordinates)
    amplicons <- subseq(valid_seqs, start = start_pos, end = end_pos)
    
    # Write to output file (append mode)
    writeXStringSet(amplicons, output_fasta, append = TRUE)
    
    total_extracted <- total_extracted + length(amplicons)
    
    # Clean up chunk
    rm(valid_seqs, amplicons)
  }
  
  # Progress report every 5 chunks
  if (chunk_id %% 5 == 0 || chunk_id == n_chunks) {
    elapsed <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))
    rate <- chunk_id / elapsed
    eta_secs <- (n_chunks - chunk_id) / rate
    
    message(sprintf("  Progress: %d/%d chunks (%.1f%%) | Extracted: %d seqs | ETA: %.1f min",
                    chunk_id, n_chunks, 100 * chunk_id / n_chunks, 
                    total_extracted, eta_secs / 60))
  }
  
  # Cleanup
  rm(chunk_seqs, all_widths, valid_indices)
  gc()
}

# --- Final Report ---
# Log extraction statistics for HPC job monitoring and debugging.
elapsed_total <- as.numeric(difftime(Sys.time(), start_time, units = "secs"))

message("========================================")
message(paste("Successfully wrote:", output_fasta))
message(paste("Total extracted sequences:", total_extracted))
message(paste("Processing time:", round(elapsed_total / 60, 2), "minutes"))
message(paste("Extraction rate:", round(n_seqs / elapsed_total), "sequences/sec"))
message("========================================")

# Final cleanup — release FASTA index before exit.
rm(fai)
gc()
